#!/bin/bash
###########
# 
# Batch convert DVD Videos with HandBrake CLI
# The script will recursively look for "VIDEO_TS" folders and parse them
# 
# Read this to understand:
# https://mattgadient.com/2013/06/12/a-best-settings-guide-for-handbrake-0-9-9/
# http://www.thewebernets.com/2015/02/28/easiest-best-optimal-settings-for-handbrake-dvd-video-conversion-on-mac-windows-and-linux/
#

inputPath=$1
outputPath=$2

transcode() {

	fileName=$1
	filePath=$2
	inputPath=$3
	outputPath=$4

	echo "Working on ${fileName}"

	### OPTIONS EXPLAINED ###################

	### VIDEO OPTIONS
	# To understand the quality (RF) setting:
	# https://mattgadient.com/2013/06/20/comparing-x264-rf-settings-in-handbrake-examples/
	OP="-q 12"

	# Level setting depends somewhat on resolution setting
	# https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Levels
	OP="$OP --encoder-level 3.1"

	### PICTURE OPTIONS 
	# Those settings resulted for most accurate output picture (close to original)
	OP="$OP --keep-display-aspect"
	OP="$OP --loose-anamorphic"

	### AUDIO OPTIONS
	# All tracks, ac3 is good enough for me
	OP="$OP --all-audio"
	OP="$OP --aencoder copy:ac3" 

	### SUBTITLE OPTIONS
	# I like to keep subtitles
	OP="$OP --all-subtitles"

	### Show time!
	HandBrakeCLI -i "${inputPath}"/"${filePath}"/"VIDEO_TS" --main-feature -o "${outputPath}"/"${fileName}".mp4 "$OP"
}

for line in $( ls $inputPath | tr ' ' '_' | tr '/' '_' ); do
	#statements
	fileName=$( echo $line )
	filePath=$( echo $line | tr '_' ' ' )
	transcode "$fileName" "$filePath" "$inputPath" "$outputPath"
done

