#!/bin/bash

inputPath=$1
outputPath=$2

log_prefix=$(echo $inputPath | tr '/' ' ' | awk '{print $2}')
missed_movie_log="$log_prefix.notdone"
init_movie_log=$(echo '' > $missed_movie_log)

transcode() {

	inputPath=$1
	outputPath=$2

	echo "Working on ${fileName}"

	OP="-q 12"
	OP="$OP --encoder-level 3.1"
	OP="$OP --keep-display-aspect"
	OP="$OP --loose-anamorphic"
	OP="$OP --all-audio"
	OP="$OP --aencoder copy:ac3" 
	OP="$OP --all-subtitles"

	for line in $( ls $inputPath | tr ' ' '_' | tr '/' '_' ); do

		fileName=$( echo $line )
		filePath=$( echo $line | tr '_' ' ' )

		HandBrakeCLI -i "${inputPath}"/"${filePath}"/"VIDEO_TS" --main-feature -o "${outputPath}"/"${fileName}".mp4 "$OP"
	done
}

check_for_missed_movies() {

	inputPath=$1
	outputPath=$2

	# loop through all movies in the input directory
	for movies in $( ls $inputPath | tr ' ' '_' | tr '/' '_' ); do

		# checks output directory against input directory
		movie_match=$(ls "${outputPath}" | grep $movies | wc -l)

		# if not transcoded, record missed movie.
		if [[ $movie_match -gt 0 ]]; then
			# pass - movie successfully transcoded
			movie_transcoded=$(echo $movies)
		else
			# fail
			movie_missed=$(echo $movies)
			echo "movie match = ${movie_match}" >> $missed_movie_log
			echo "${movies}" >> $missed_movie_log
			echo '-------------------------------------' >> $missed_movie_log
		fi
	done
}

transcode "$inputPath" "$outputPath"

check_for_missed_movies "$inputPath" "$outputPath"
